{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1bd8ca91",
   "metadata": {},
   "source": [
    "# Reddit image scraper"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b4cfcf92",
   "metadata": {},
   "source": [
    "**How to run the scraper :**\n",
    "\n",
    "%run RedditImageScraper\\SubDownload.py \n",
    "\n",
    "- arg1 : subreddit_name\n",
    "- arg2 : Nb of images you want to save (~500 per subreddit needed), max limit :100.000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a59e1c73",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting parsing images from r/gonewild!\n",
      "Saving folder : E:/Projets/GANbang/Data/Reddit_images \n",
      "\n",
      "1 valid image saved\n",
      "2 valid image saved\n",
      "3 valid image saved\n",
      "4 valid image saved\n",
      "5 valid image saved\n",
      "6 valid image saved\n",
      "7 valid image saved\n",
      "8 valid image saved\n",
      "9 valid image saved\n",
      "10 valid image saved\n",
      "11 valid image saved\n",
      "12 valid image saved\n",
      "13 valid image saved\n",
      "14 valid image saved\n",
      "15 valid image saved\n",
      "16 valid image saved\n",
      "17 valid image saved\n",
      "18 valid image saved\n",
      "19 valid image saved\n",
      "20 valid image saved\n",
      "21 valid image saved\n",
      "22 valid image saved\n",
      "23 valid image saved\n",
      "24 valid image saved\n",
      "25 valid image saved\n",
      "26 valid image saved\n",
      "27 valid image saved\n",
      "28 valid image saved\n",
      "29 valid image saved\n",
      "30 valid image saved\n",
      "31 valid image saved\n",
      "32 valid image saved\n",
      "33 valid image saved\n",
      "34 valid image saved\n",
      "35 valid image saved\n",
      "36 valid image saved\n",
      "37 valid image saved\n",
      "38 valid image saved\n",
      "39 valid image saved\n",
      "40 valid image saved\n",
      "41 valid image saved\n",
      "42 valid image saved\n",
      "43 valid image saved\n",
      "44 valid image saved\n",
      "45 valid image saved\n",
      "46 valid image saved\n",
      "47 valid image saved\n",
      "48 valid image saved\n",
      "49 valid image saved\n",
      "50 valid image saved\n",
      "51 valid image saved\n",
      "52 valid image saved\n",
      "53 valid image saved\n",
      "54 valid image saved\n",
      "55 valid image saved\n",
      "56 valid image saved\n",
      "57 valid image saved\n",
      "58 valid image saved\n",
      "59 valid image saved\n",
      "60 valid image saved\n",
      "61 valid image saved\n",
      "62 valid image saved\n",
      "63 valid image saved\n",
      "64 valid image saved\n",
      "65 valid image saved\n",
      "66 valid image saved\n",
      "67 valid image saved\n",
      "68 valid image saved\n",
      "69 valid image saved\n",
      "70 valid image saved\n",
      "71 valid image saved\n",
      "72 valid image saved\n",
      "73 valid image saved\n",
      "74 valid image saved\n",
      "75 valid image saved\n",
      "76 valid image saved\n",
      "77 valid image saved\n",
      "78 valid image saved\n",
      "79 valid image saved\n",
      "80 valid image saved\n",
      "81 valid image saved\n",
      "82 valid image saved\n",
      "83 valid image saved\n",
      "84 valid image saved\n",
      "85 valid image saved\n",
      "86 valid image saved\n",
      "87 valid image saved\n",
      "88 valid image saved\n",
      "89 valid image saved\n",
      "90 valid image saved\n",
      "91 valid image saved\n",
      "92 valid image saved\n",
      "93 valid image saved\n",
      "94 valid image saved\n",
      "95 valid image saved\n",
      "96 valid image saved\n",
      "97 valid image saved\n",
      "98 valid image saved\n",
      "99 valid image saved\n",
      "100 valid image saved\n",
      "101 valid image saved\n",
      "102 valid image saved\n",
      "103 valid image saved\n",
      "104 valid image saved\n",
      "105 valid image saved\n",
      "106 valid image saved\n",
      "107 valid image saved\n",
      "108 valid image saved\n",
      "109 valid image saved\n",
      "110 valid image saved\n",
      "111 valid image saved\n",
      "112 valid image saved\n",
      "113 valid image saved\n",
      "114 valid image saved\n",
      "115 valid image saved\n",
      "116 valid image saved\n",
      "117 valid image saved\n",
      "118 valid image saved\n",
      "119 valid image saved\n",
      "120 valid image saved\n",
      "121 valid image saved\n",
      "122 valid image saved\n",
      "123 valid image saved\n",
      "124 valid image saved\n",
      "125 valid image saved\n",
      "126 valid image saved\n",
      "127 valid image saved\n",
      "128 valid image saved\n",
      "129 valid image saved\n",
      "130 valid image saved\n",
      "131 valid image saved\n",
      "132 valid image saved\n",
      "133 valid image saved\n",
      "134 valid image saved\n",
      "135 valid image saved\n",
      "136 valid image saved\n",
      "137 valid image saved\n",
      "138 valid image saved\n",
      "139 valid image saved\n",
      "140 valid image saved\n",
      "141 valid image saved\n",
      "142 valid image saved\n",
      "143 valid image saved\n",
      "144 valid image saved\n",
      "145 valid image saved\n",
      "146 valid image saved\n",
      "147 valid image saved\n",
      "148 valid image saved\n",
      "149 valid image saved\n",
      "150 valid image saved\n",
      "151 valid image saved\n",
      "152 valid image saved\n",
      "153 valid image saved\n",
      "154 valid image saved\n",
      "155 valid image saved\n",
      "156 valid image saved\n",
      "157 valid image saved\n",
      "158 valid image saved\n",
      "159 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/235305724_907005009884135_5950957128078915602_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=ae9488&_nc_ohc=nqrx7mqspdwax9efaxg&_nc_ht=scontent.fltn2-1.fna&oh=203cb10f233905b4b71e9f28f93a34d3&oe=613f520c\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "160 valid image saved\n",
      "161 valid image saved\n",
      "162 valid image saved\n",
      "163 valid image saved\n",
      "164 valid image saved\n",
      "165 valid image saved\n",
      "166 valid image saved\n",
      "167 valid image saved\n",
      "168 valid image saved\n",
      "169 valid image saved\n",
      "170 valid image saved\n",
      "171 valid image saved\n",
      "172 valid image saved\n",
      "173 valid image saved\n",
      "Image failed. https://imgur.com/a/qkgsczv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "174 valid image saved\n",
      "Image failed. https://imgur.com/a/qkgsczv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "175 valid image saved\n",
      "176 valid image saved\n",
      "177 valid image saved\n",
      "178 valid image saved\n",
      "179 valid image saved\n",
      "180 valid image saved\n",
      "Image failed. https://imgur.com/a/8ffgdxc.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "181 valid image saved\n",
      "182 valid image saved\n",
      "183 valid image saved\n",
      "184 valid image saved\n",
      "185 valid image saved\n",
      "186 valid image saved\n",
      "187 valid image saved\n",
      "188 valid image saved\n",
      "189 valid image saved\n",
      "190 valid image saved\n",
      "191 valid image saved\n",
      "192 valid image saved\n",
      "193 valid image saved\n",
      "194 valid image saved\n",
      "195 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/235867282_519734275976016_459557787261112699_n.jpg?_nc_cat=109&ccb=1-5&_nc_sid=ae9488&_nc_ohc=nmjexpraevuax9ec6zi&_nc_ht=scontent.fltn2-1.fna&oh=2b80586f17a41b0bd95501c996654431&oe=614200b0\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "196 valid image saved\n",
      "197 valid image saved\n",
      "198 valid image saved\n",
      "199 valid image saved\n",
      "200 valid image saved\n",
      "Image failed. https://i.imgur.com/never felt this turned on!! lets have some fun!o5wol.png\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgcodecs\\src\\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'\n",
      "\n",
      "201 valid image saved\n",
      "202 valid image saved\n",
      "203 valid image saved\n",
      "204 valid image saved\n",
      "205 valid image saved\n",
      "206 valid image saved\n",
      "207 valid image saved\n",
      "208 valid image saved\n",
      "209 valid image saved\n",
      "210 valid image saved\n",
      "211 valid image saved\n",
      "212 valid image saved\n",
      "Image failed. https://imgur.com/a/tcgjsaq.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "213 valid image saved\n",
      "Image failed. https://imgur.com/a/onlmquw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "214 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/221539738_4015009401958957_692898539824498119_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=ae9488&_nc_ohc=mohoi9i5ny4ax9omkx6&_nc_ht=scontent.fltn2-1.fna&oh=4f2fc230006295c0c1e85b4da83954b5&oe=613ea307\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/234327359_251555316800879_3442988150309688504_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=ae9488&_nc_ohc=lvfvmtpfmzcax917_vd&_nc_ht=scontent.fltn2-1.fna&oh=5d46eb244c103c7a66fa4c1165e96db4&oe=613ddd7c\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "215 valid image saved\n",
      "216 valid image saved\n",
      "217 valid image saved\n",
      "Image failed. https://www.dropbox.com/s/x8lqiyzebrdaw7w/1.jpg?raw=1\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "218 valid image saved\n",
      "Image failed. https://imgur.com/a/ebip4ha.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/jzbo2rs.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/svkforh.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/onlmquw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/hkna0d0.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/hkna0d0.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "219 valid image saved\n",
      "220 valid image saved\n",
      "221 valid image saved\n",
      "222 valid image saved\n",
      "223 valid image saved\n",
      "224 valid image saved\n",
      "225 valid image saved\n",
      "226 valid image saved\n",
      "227 valid image saved\n",
      "228 valid image saved\n",
      "229 valid image saved\n",
      "230 valid image saved\n",
      "231 valid image saved\n",
      "232 valid image saved\n",
      "233 valid image saved\n",
      "234 valid image saved\n",
      "235 valid image saved\n",
      "236 valid image saved\n",
      "237 valid image saved\n",
      "238 valid image saved\n",
      "239 valid image saved\n",
      "240 valid image saved\n",
      "241 valid image saved\n",
      "242 valid image saved\n",
      "Image failed. https://imgur.com/a/kscfvkl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "243 valid image saved\n",
      "244 valid image saved\n",
      "245 valid image saved\n",
      "246 valid image saved\n",
      "247 valid image saved\n",
      "248 valid image saved\n",
      "249 valid image saved\n",
      "250 valid image saved\n",
      "251 valid image saved\n",
      "252 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/233659106_903340136949550_8771689215022436656_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=ae9488&_nc_ohc=pxhlwuviyhgax_kfhwp&_nc_ht=scontent.fltn2-1.fna&oh=3fa671efc06ea07ef23db4cda417ea1b&oe=613e01d0\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/229839711_3299237170310109_280572160019447149_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=ae9488&_nc_ohc=v0-kkix2mpwax8pnkyw&_nc_ht=scontent.fltn2-1.fna&oh=38c5b0bc9a691d9616a0a60ac7afa510&oe=613d4a86\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/229839711_3299237170310109_280572160019447149_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=ae9488&_nc_ohc=v0-kkix2mpwax8pnkyw&_nc_ht=scontent.fltn2-1.fna&oh=38c5b0bc9a691d9616a0a60ac7afa510&oe=613d4a86\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "253 valid image saved\n",
      "254 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/228586397_373428837551371_6083099178921530841_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=ae9488&_nc_ohc=enlszxlpbduax9mn6qo&_nc_ht=scontent.fltn2-1.fna&oh=1ed1f588c21a79efd78636026313dadf&oe=613c78a8\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "255 valid image saved\n",
      "256 valid image saved\n",
      "257 valid image saved\n",
      "258 valid image saved\n",
      "259 valid image saved\n",
      "260 valid image saved\n",
      "261 valid image saved\n",
      "262 valid image saved\n",
      "263 valid image saved\n",
      "264 valid image saved\n",
      "265 valid image saved\n",
      "266 valid image saved\n",
      "267 valid image saved\n",
      "268 valid image saved\n",
      "269 valid image saved\n",
      "270 valid image saved\n",
      "271 valid image saved\n",
      "272 valid image saved\n",
      "273 valid image saved\n",
      "274 valid image saved\n",
      "275 valid image saved\n",
      "276 valid image saved\n",
      "277 valid image saved\n",
      "278 valid image saved\n",
      "279 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/228620132_5896451937095654_8756119792679204192_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=ae9488&_nc_ohc=vwdfhzcfndkax_rkcms&_nc_ht=scontent.fltn2-1.fna&oh=7e8bcc1046564bf21a8eaf41c157fc7f&oe=613d2795\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/228620132_5896451937095654_8756119792679204192_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=ae9488&_nc_ohc=vwdfhzcfndkax_rkcms&_nc_ht=scontent.fltn2-1.fna&oh=7e8bcc1046564bf21a8eaf41c157fc7f&oe=613d2795\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "280 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/232143949_318602959992593_1123820601894580220_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=ae9488&_nc_ohc=qrp3gawkh-oax9msc9m&_nc_ht=scontent.fltn2-1.fna&oh=070f308dc166a7e34b83c48ea0a21ac6&oe=613e7662\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/s1080x2048/234238730_4306485876072283_2530583044190372294_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=yfbwktxevykax9sxxjc&_nc_ht=scontent.fltn2-1.fna&oh=d7374cecd2a2b5c5a56c89ec42342981&oe=613ccdc8\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "281 valid image saved\n",
      "Image failed. http://14/8/2021 lenauk2021 r/gonewild https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/s1080x2048/234238730_4306485876072283_2530583044190372294_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=yfbwktxevykax9sxxjc&_nc_ht=scontent.fltn2-1.fna&oh=d7374cecd2a2b5c5a56c89ec42342981&oe=613ccdc8\n",
      "HTTPConnectionPool(host='14', port=80): Max retries exceeded with url: /8/2021%20lenauk2021%20r/gonewild%20https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/s1080x2048/234238730_4306485876072283_2530583044190372294_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=yfbwktxevykax9sxxjc&_nc_ht=scontent.fltn2-1.fna&oh=d7374cecd2a2b5c5a56c89ec42342981&oe=613ccdc8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206555CF130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "282 valid image saved\n",
      "283 valid image saved\n",
      "Image failed. https://scontent.fltn2-1.fna.fbcdn.net/v/t1.15752-9/p1080x2048/229647570_549960993116771_3919495320438665480_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=em_jhysijz0ax_3sxsg&_nc_oc=aqle3aoukcuk_lgb0m0vitdvqbyd5jadyrq1bepfv2z9ql6ba73keplrdpu--4gptsi&_nc_ht=scontent.fltn2-1.fna&oh=6bfc69453fc6db33ca7d66ddfaf58496&oe=613e6ec0\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "284 valid image saved\n",
      "285 valid image saved\n",
      "286 valid image saved\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "287 valid image saved\n",
      "288 valid image saved\n",
      "289 valid image saved\n",
      "290 valid image saved\n",
      "291 valid image saved\n",
      "292 valid image saved\n",
      "293 valid image saved\n",
      "294 valid image saved\n",
      "295 valid image saved\n",
      "296 valid image saved\n",
      "297 valid image saved\n",
      "298 valid image saved\n",
      "Image failed. https://imgur.com/a/exmcgzn.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "299 valid image saved\n",
      "300 valid image saved\n",
      "301 valid image saved\n",
      "302 valid image saved\n",
      "303 valid image saved\n",
      "304 valid image saved\n",
      "305 valid image saved\n",
      "306 valid image saved\n",
      "307 valid image saved\n",
      "308 valid image saved\n",
      "309 valid image saved\n",
      "310 valid image saved\n",
      "311 valid image saved\n",
      "312 valid image saved\n",
      "313 valid image saved\n",
      "314 valid image saved\n",
      "315 valid image saved\n",
      "316 valid image saved\n",
      "317 valid image saved\n",
      "Image failed. https://i.imgur.com/a/6ssdxvv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "318 valid image saved\n",
      "319 valid image saved\n",
      "320 valid image saved\n",
      "321 valid image saved\n",
      "322 valid image saved\n",
      "323 valid image saved\n",
      "324 valid image saved\n",
      "325 valid image saved\n",
      "326 valid image saved\n",
      "327 valid image saved\n",
      "328 valid image saved\n",
      "329 valid image saved\n",
      "330 valid image saved\n",
      "331 valid image saved\n",
      "Image failed. https://i.imgur.com/a/gn4lxgc.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "332 valid image saved\n",
      "333 valid image saved\n",
      "334 valid image saved\n",
      "335 valid image saved\n",
      "336 valid image saved\n",
      "337 valid image saved\n",
      "338 valid image saved\n",
      "339 valid image saved\n",
      "340 valid image saved\n",
      "341 valid image saved\n",
      "342 valid image saved\n",
      "343 valid image saved\n",
      "344 valid image saved\n",
      "345 valid image saved\n",
      "346 valid image saved\n",
      "347 valid image saved\n",
      "348 valid image saved\n",
      "349 valid image saved\n",
      "350 valid image saved\n",
      "351 valid image saved\n",
      "352 valid image saved\n",
      "353 valid image saved\n",
      "354 valid image saved\n",
      "355 valid image saved\n",
      "356 valid image saved\n",
      "357 valid image saved\n",
      "358 valid image saved\n",
      "359 valid image saved\n",
      "360 valid image saved\n",
      "361 valid image saved\n",
      "362 valid image saved\n",
      "363 valid image saved\n",
      "364 valid image saved\n",
      "365 valid image saved\n",
      "366 valid image saved\n",
      "367 valid image saved\n",
      "368 valid image saved\n",
      "369 valid image saved\n",
      "370 valid image saved\n",
      "371 valid image saved\n",
      "372 valid image saved\n",
      "373 valid image saved\n",
      "374 valid image saved\n",
      "Image failed. https://imgur.com/a/vx40dqz.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "375 valid image saved\n",
      "376 valid image saved\n",
      "377 valid image saved\n",
      "378 valid image saved\n",
      "379 valid image saved\n",
      "380 valid image saved\n",
      "381 valid image saved\n",
      "382 valid image saved\n",
      "Image failed. https://imgur.com/a/ni9pny4.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/fcsm4oo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/fcsm4oo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "383 valid image saved\n",
      "384 valid image saved\n",
      "385 valid image saved\n",
      "386 valid image saved\n",
      "387 valid image saved\n",
      "388 valid image saved\n",
      "389 valid image saved\n",
      "390 valid image saved\n",
      "391 valid image saved\n",
      "392 valid image saved\n",
      "393 valid image saved\n",
      "394 valid image saved\n",
      "395 valid image saved\n",
      "396 valid image saved\n",
      "397 valid image saved\n",
      "398 valid image saved\n",
      "399 valid image saved\n",
      "Image failed. https://imgur.com/a/2tmhq4c.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "400 valid image saved\n",
      "401 valid image saved\n",
      "Image failed. https://www.dropbox.com/s/sep20d7d4ya4r5u/tinasherance_64599739_451354789022205_8894509474307077454_n.jpg?dl=0\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "402 valid image saved\n",
      "403 valid image saved\n",
      "404 valid image saved\n",
      "405 valid image saved\n",
      "406 valid image saved\n",
      "407 valid image saved\n",
      "408 valid image saved\n",
      "409 valid image saved\n",
      "410 valid image saved\n",
      "411 valid image saved\n",
      "Image failed. https://i.imgur.com/rww6xi’m so horny and bored right now.png\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgcodecs\\src\\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'\n",
      "\n",
      "412 valid image saved\n",
      "413 valid image saved\n",
      "414 valid image saved\n",
      "415 valid image saved\n",
      "416 valid image saved\n",
      "417 valid image saved\n",
      "418 valid image saved\n",
      "419 valid image saved\n",
      "420 valid image saved\n",
      "421 valid image saved\n",
      "422 valid image saved\n",
      "423 valid image saved\n",
      "424 valid image saved\n",
      "425 valid image saved\n",
      "426 valid image saved\n",
      "427 valid image saved\n",
      "428 valid image saved\n",
      "429 valid image saved\n",
      "430 valid image saved\n",
      "Image failed. https://imgur.com/a/mhpyiwd.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/855bisb.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "431 valid image saved\n",
      "Image failed. https://imgur.com/a/t4vhtx8.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/0qxbbte.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "432 valid image saved\n",
      "433 valid image saved\n",
      "434 valid image saved\n",
      "435 valid image saved\n",
      "436 valid image saved\n",
      "Image failed. https://imgur.com/a/uxf7a4n.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/rexroqn.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "437 valid image saved\n",
      "Image failed. https://imgur.com/a/xx4r2ff.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "438 valid image saved\n",
      "439 valid image saved\n",
      "440 valid image saved\n",
      "441 valid image saved\n",
      "442 valid image saved\n",
      "443 valid image saved\n",
      "444 valid image saved\n",
      "445 valid image saved\n",
      "446 valid image saved\n",
      "447 valid image saved\n",
      "448 valid image saved\n",
      "449 valid image saved\n",
      "450 valid image saved\n",
      "451 valid image saved\n",
      "452 valid image saved\n",
      "453 valid image saved\n",
      "454 valid image saved\n",
      "455 valid image saved\n",
      "456 valid image saved\n",
      "457 valid image saved\n",
      "458 valid image saved\n",
      "459 valid image saved\n",
      "460 valid image saved\n",
      "461 valid image saved\n",
      "462 valid image saved\n",
      "463 valid image saved\n",
      "464 valid image saved\n",
      "465 valid image saved\n",
      "466 valid image saved\n",
      "467 valid image saved\n",
      "468 valid image saved\n",
      "469 valid image saved\n",
      "470 valid image saved\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "471 valid image saved\n",
      "472 valid image saved\n",
      "473 valid image saved\n",
      "474 valid image saved\n",
      "475 valid image saved\n",
      "476 valid image saved\n",
      "477 valid image saved\n",
      "478 valid image saved\n",
      "479 valid image saved\n",
      "480 valid image saved\n",
      "481 valid image saved\n",
      "482 valid image saved\n",
      "483 valid image saved\n",
      "484 valid image saved\n",
      "485 valid image saved\n",
      "Image failed. https://imgur.com/a/kscfvkl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "486 valid image saved\n",
      "487 valid image saved\n",
      "488 valid image saved\n",
      "489 valid image saved\n",
      "490 valid image saved\n",
      "491 valid image saved\n",
      "492 valid image saved\n",
      "493 valid image saved\n",
      "494 valid image saved\n",
      "Image failed. https://imgur.com/a/7yrsvuz.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "495 valid image saved\n",
      "496 valid image saved\n",
      "497 valid image saved\n",
      "498 valid image saved\n",
      "499 valid image saved\n",
      "Image failed. https://imgur.com/a/x7jnqp8.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "500 valid image saved\n",
      "Image failed. https://imgur.com/a/iadelhv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "501 valid image saved\n",
      "502 valid image saved\n",
      "Image failed. https://imgur.com/a/rbkzbco.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/9wqyht5.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/6yusfa1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "503 valid image saved\n",
      "Image failed. https://imgur.com/a/6yusfa1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "504 valid image saved\n",
      "505 valid image saved\n",
      "506 valid image saved\n",
      "507 valid image saved\n",
      "508 valid image saved\n",
      "509 valid image saved\n",
      "510 valid image saved\n",
      "511 valid image saved\n",
      "512 valid image saved\n",
      "513 valid image saved\n",
      "514 valid image saved\n",
      "515 valid image saved\n",
      "516 valid image saved\n",
      "517 valid image saved\n",
      "518 valid image saved\n",
      "519 valid image saved\n",
      "520 valid image saved\n",
      "521 valid image saved\n",
      "Image failed. https://pbs.twimg.com/profile_images/888962665837715456/tlvrztbf_400x400.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgcodecs\\src\\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'\n",
      "\n",
      "522 valid image saved\n",
      "523 valid image saved\n",
      "524 valid image saved\n",
      "525 valid image saved\n",
      "526 valid image saved\n",
      "527 valid image saved\n",
      "528 valid image saved\n",
      "529 valid image saved\n",
      "530 valid image saved\n",
      "531 valid image saved\n",
      "532 valid image saved\n",
      "533 valid image saved\n",
      "534 valid image saved\n",
      "535 valid image saved\n",
      "536 valid image saved\n",
      "537 valid image saved\n",
      "538 valid image saved\n",
      "539 valid image saved\n",
      "540 valid image saved\n",
      "Image failed. https://imgur.com/a/4sdmzny.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "541 valid image saved\n",
      "542 valid image saved\n",
      "543 valid image saved\n",
      "544 valid image saved\n",
      "545 valid image saved\n",
      "Image failed. https://imgur.com/a/xqjqx43.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "546 valid image saved\n",
      "Image failed. https://imgur.com/a/gv0t6yp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/7dzme2l.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "547 valid image saved\n",
      "548 valid image saved\n",
      "Image failed. https://imgur.com/a/fuo1nsc.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "549 valid image saved\n",
      "550 valid image saved\n",
      "551 valid image saved\n",
      "552 valid image saved\n",
      "553 valid image saved\n",
      "554 valid image saved\n",
      "555 valid image saved\n",
      "556 valid image saved\n",
      "557 valid image saved\n",
      "558 valid image saved\n",
      "559 valid image saved\n",
      "560 valid image saved\n",
      "561 valid image saved\n",
      "562 valid image saved\n",
      "563 valid image saved\n",
      "564 valid image saved\n",
      "565 valid image saved\n",
      "566 valid image saved\n",
      "567 valid image saved\n",
      "568 valid image saved\n",
      "569 valid image saved\n",
      "570 valid image saved\n",
      "571 valid image saved\n",
      "572 valid image saved\n",
      "573 valid image saved\n",
      "574 valid image saved\n",
      "575 valid image saved\n",
      "576 valid image saved\n",
      "577 valid image saved\n",
      "Image failed. https://imgur.com/a/uzjh7jg.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "578 valid image saved\n",
      "579 valid image saved\n",
      "580 valid image saved\n",
      "581 valid image saved\n",
      "582 valid image saved\n",
      "Image failed. https://imgur.com/a/wkfwmsz.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "583 valid image saved\n",
      "584 valid image saved\n",
      "585 valid image saved\n",
      "Image failed. https://imgur.com/a/fuo1nsc.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "586 valid image saved\n",
      "587 valid image saved\n",
      "588 valid image saved\n",
      "589 valid image saved\n",
      "590 valid image saved\n",
      "591 valid image saved\n",
      "592 valid image saved\n",
      "593 valid image saved\n",
      "594 valid image saved\n",
      "595 valid image saved\n",
      "596 valid image saved\n",
      "597 valid image saved\n",
      "598 valid image saved\n",
      "599 valid image saved\n",
      "600 valid image saved\n",
      "601 valid image saved\n",
      "602 valid image saved\n",
      "603 valid image saved\n",
      "604 valid image saved\n",
      "605 valid image saved\n",
      "606 valid image saved\n",
      "607 valid image saved\n",
      "608 valid image saved\n",
      "609 valid image saved\n",
      "610 valid image saved\n",
      "611 valid image saved\n",
      "612 valid image saved\n",
      "613 valid image saved\n",
      "614 valid image saved\n",
      "615 valid image saved\n",
      "616 valid image saved\n",
      "617 valid image saved\n",
      "618 valid image saved\n",
      "619 valid image saved\n",
      "620 valid image saved\n",
      "621 valid image saved\n",
      "622 valid image saved\n",
      "623 valid image saved\n",
      "624 valid image saved\n",
      "625 valid image saved\n",
      "626 valid image saved\n",
      "627 valid image saved\n",
      "Image failed. http://imgur.com/a/blie99r.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "628 valid image saved\n",
      "629 valid image saved\n",
      "630 valid image saved\n",
      "631 valid image saved\n",
      "632 valid image saved\n",
      "633 valid image saved\n",
      "634 valid image saved\n",
      "635 valid image saved\n",
      "636 valid image saved\n",
      "637 valid image saved\n",
      "638 valid image saved\n",
      "639 valid image saved\n",
      "640 valid image saved\n",
      "641 valid image saved\n",
      "642 valid image saved\n",
      "643 valid image saved\n",
      "644 valid image saved\n",
      "645 valid image saved\n",
      "646 valid image saved\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "647 valid image saved\n",
      "648 valid image saved\n",
      "649 valid image saved\n",
      "650 valid image saved\n",
      "651 valid image saved\n",
      "652 valid image saved\n",
      "653 valid image saved\n",
      "654 valid image saved\n",
      "655 valid image saved\n",
      "656 valid image saved\n",
      "657 valid image saved\n",
      "Image failed. https://imgur.com/a/4zoeatb.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/2gpnkpo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "658 valid image saved\n",
      "659 valid image saved\n",
      "660 valid image saved\n",
      "Image failed. https://imgur.com/a/dsi1wj3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "661 valid image saved\n",
      "662 valid image saved\n",
      "663 valid image saved\n",
      "664 valid image saved\n",
      "665 valid image saved\n",
      "666 valid image saved\n",
      "667 valid image saved\n",
      "668 valid image saved\n",
      "669 valid image saved\n",
      "670 valid image saved\n",
      "671 valid image saved\n",
      "672 valid image saved\n",
      "673 valid image saved\n",
      "674 valid image saved\n",
      "675 valid image saved\n",
      "676 valid image saved\n",
      "677 valid image saved\n",
      "678 valid image saved\n",
      "679 valid image saved\n",
      "680 valid image saved\n",
      "681 valid image saved\n",
      "682 valid image saved\n",
      "683 valid image saved\n",
      "684 valid image saved\n",
      "685 valid image saved\n",
      "686 valid image saved\n",
      "687 valid image saved\n",
      "688 valid image saved\n",
      "689 valid image saved\n",
      "690 valid image saved\n",
      "691 valid image saved\n",
      "692 valid image saved\n",
      "693 valid image saved\n",
      "694 valid image saved\n",
      "695 valid image saved\n",
      "696 valid image saved\n",
      "697 valid image saved\n",
      "698 valid image saved\n",
      "699 valid image saved\n",
      "700 valid image saved\n",
      "701 valid image saved\n",
      "702 valid image saved\n",
      "703 valid image saved\n",
      "704 valid image saved\n",
      "705 valid image saved\n",
      "706 valid image saved\n",
      "707 valid image saved\n",
      "708 valid image saved\n",
      "709 valid image saved\n",
      "710 valid image saved\n",
      "711 valid image saved\n",
      "712 valid image saved\n",
      "713 valid image saved\n",
      "714 valid image saved\n",
      "715 valid image saved\n",
      "716 valid image saved\n",
      "717 valid image saved\n",
      "718 valid image saved\n",
      "719 valid image saved\n",
      "720 valid image saved\n",
      "721 valid image saved\n",
      "722 valid image saved\n",
      "723 valid image saved\n",
      "Image failed. https://imgur.com/a/se1ehly.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "724 valid image saved\n",
      "725 valid image saved\n",
      "726 valid image saved\n",
      "727 valid image saved\n",
      "728 valid image saved\n",
      "729 valid image saved\n",
      "730 valid image saved\n",
      "731 valid image saved\n",
      "732 valid image saved\n",
      "733 valid image saved\n",
      "734 valid image saved\n",
      "735 valid image saved\n",
      "736 valid image saved\n",
      "737 valid image saved\n",
      "738 valid image saved\n",
      "739 valid image saved\n",
      "740 valid image saved\n",
      "741 valid image saved\n",
      "742 valid image saved\n",
      "743 valid image saved\n",
      "744 valid image saved\n",
      "745 valid image saved\n",
      "746 valid image saved\n",
      "747 valid image saved\n",
      "748 valid image saved\n",
      "749 valid image saved\n",
      "750 valid image saved\n",
      "751 valid image saved\n",
      "752 valid image saved\n",
      "753 valid image saved\n",
      "754 valid image saved\n",
      "755 valid image saved\n",
      "756 valid image saved\n",
      "757 valid image saved\n",
      "758 valid image saved\n",
      "759 valid image saved\n",
      "Image failed. https://external-preview.redd.it/_r1wfvie3vcsnutp_j4jef7sepwdqxaa2fdq7qfve2q.png?auto=webp&s=92192043cb2080ca61dc8e775a954e4880b7d06b\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "760 valid image saved\n",
      "761 valid image saved\n",
      "762 valid image saved\n",
      "763 valid image saved\n",
      "764 valid image saved\n",
      "765 valid image saved\n",
      "766 valid image saved\n",
      "767 valid image saved\n",
      "768 valid image saved\n",
      "769 valid image saved\n",
      "770 valid image saved\n",
      "771 valid image saved\n",
      "Image failed. https://imgur.com/a/u1llo2z.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "772 valid image saved\n",
      "773 valid image saved\n",
      "774 valid image saved\n",
      "775 valid image saved\n",
      "Image failed. https://external-preview.redd.it/yp_llxsr0koiu-uu60tfovsfdkbtloqkxair8lbkonq.jpg?auto=webp&s=f4eebae3ddd4e770a8330abe05ce5ae28e466a47\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "776 valid image saved\n",
      "777 valid image saved\n",
      "778 valid image saved\n",
      "779 valid image saved\n",
      "780 valid image saved\n",
      "781 valid image saved\n",
      "782 valid image saved\n",
      "783 valid image saved\n",
      "784 valid image saved\n",
      "785 valid image saved\n",
      "786 valid image saved\n",
      "787 valid image saved\n",
      "788 valid image saved\n",
      "789 valid image saved\n",
      "790 valid image saved\n",
      "791 valid image saved\n",
      "792 valid image saved\n",
      "793 valid image saved\n",
      "794 valid image saved\n",
      "795 valid image saved\n",
      "796 valid image saved\n",
      "797 valid image saved\n",
      "798 valid image saved\n",
      "799 valid image saved\n",
      "800 valid image saved\n",
      "801 valid image saved\n",
      "802 valid image saved\n",
      "803 valid image saved\n",
      "804 valid image saved\n",
      "805 valid image saved\n",
      "Image failed. https://imgur.com/a/nng38et.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/pbctnu1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "806 valid image saved\n",
      "807 valid image saved\n",
      "808 valid image saved\n",
      "Image failed. https://imgur.com/a/o7xdujs.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/0qxbbte.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "809 valid image saved\n",
      "810 valid image saved\n",
      "811 valid image saved\n",
      "812 valid image saved\n",
      "813 valid image saved\n",
      "814 valid image saved\n",
      "815 valid image saved\n",
      "816 valid image saved\n",
      "Image failed. https://imgur.com/a/0qxbbte.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "817 valid image saved\n",
      "818 valid image saved\n",
      "819 valid image saved\n",
      "820 valid image saved\n",
      "821 valid image saved\n",
      "822 valid image saved\n",
      "823 valid image saved\n",
      "824 valid image saved\n",
      "825 valid image saved\n",
      "826 valid image saved\n",
      "827 valid image saved\n",
      "828 valid image saved\n",
      "829 valid image saved\n",
      "830 valid image saved\n",
      "831 valid image saved\n",
      "832 valid image saved\n",
      "833 valid image saved\n",
      "834 valid image saved\n",
      "835 valid image saved\n",
      "836 valid image saved\n",
      "837 valid image saved\n",
      "838 valid image saved\n",
      "839 valid image saved\n",
      "840 valid image saved\n",
      "841 valid image saved\n",
      "842 valid image saved\n",
      "843 valid image saved\n",
      "844 valid image saved\n",
      "845 valid image saved\n",
      "846 valid image saved\n",
      "847 valid image saved\n",
      "848 valid image saved\n",
      "849 valid image saved\n",
      "850 valid image saved\n",
      "851 valid image saved\n",
      "852 valid image saved\n",
      "853 valid image saved\n",
      "854 valid image saved\n",
      "Image failed. https://imgur.com/a/zbujtn3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/6yusfa1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "855 valid image saved\n",
      "856 valid image saved\n",
      "Image failed. https://imgur.com/a/ugaxf6t.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "857 valid image saved\n",
      "858 valid image saved\n",
      "859 valid image saved\n",
      "860 valid image saved\n",
      "861 valid image saved\n",
      "862 valid image saved\n",
      "863 valid image saved\n",
      "864 valid image saved\n",
      "865 valid image saved\n",
      "866 valid image saved\n",
      "867 valid image saved\n",
      "868 valid image saved\n",
      "869 valid image saved\n",
      "870 valid image saved\n",
      "871 valid image saved\n",
      "872 valid image saved\n",
      "873 valid image saved\n",
      "874 valid image saved\n",
      "875 valid image saved\n",
      "876 valid image saved\n",
      "877 valid image saved\n",
      "878 valid image saved\n",
      "879 valid image saved\n",
      "880 valid image saved\n",
      "881 valid image saved\n",
      "882 valid image saved\n",
      "883 valid image saved\n",
      "884 valid image saved\n",
      "885 valid image saved\n",
      "886 valid image saved\n",
      "887 valid image saved\n",
      "888 valid image saved\n",
      "889 valid image saved\n",
      "890 valid image saved\n",
      "891 valid image saved\n",
      "892 valid image saved\n",
      "893 valid image saved\n",
      "894 valid image saved\n",
      "895 valid image saved\n",
      "896 valid image saved\n",
      "897 valid image saved\n",
      "898 valid image saved\n",
      "Image failed. https://imgur.com/a/k5xgear.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/a5gbvde.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "899 valid image saved\n",
      "900 valid image saved\n",
      "901 valid image saved\n",
      "902 valid image saved\n",
      "Image failed. https://imgur.com/a/n9luv7g.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "903 valid image saved\n",
      "904 valid image saved\n",
      "905 valid image saved\n",
      "906 valid image saved\n",
      "907 valid image saved\n",
      "908 valid image saved\n",
      "909 valid image saved\n",
      "910 valid image saved\n",
      "911 valid image saved\n",
      "Image failed. https://imgur.com/a/u5gwp4i.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "912 valid image saved\n",
      "Image failed. https://imgur.com/a/edkzymj.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/vaduzea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "913 valid image saved\n",
      "914 valid image saved\n",
      "915 valid image saved\n",
      "916 valid image saved\n",
      "917 valid image saved\n",
      "918 valid image saved\n",
      "919 valid image saved\n",
      "920 valid image saved\n",
      "921 valid image saved\n",
      "922 valid image saved\n",
      "923 valid image saved\n",
      "924 valid image saved\n",
      "925 valid image saved\n",
      "926 valid image saved\n",
      "927 valid image saved\n",
      "928 valid image saved\n",
      "929 valid image saved\n",
      "930 valid image saved\n",
      "Image failed. https://imgur.com/a/kscfvkl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "931 valid image saved\n",
      "932 valid image saved\n",
      "933 valid image saved\n",
      "934 valid image saved\n",
      "935 valid image saved\n",
      "936 valid image saved\n",
      "937 valid image saved\n",
      "938 valid image saved\n",
      "939 valid image saved\n",
      "940 valid image saved\n",
      "941 valid image saved\n",
      "942 valid image saved\n",
      "943 valid image saved\n",
      "944 valid image saved\n",
      "945 valid image saved\n",
      "946 valid image saved\n",
      "947 valid image saved\n",
      "948 valid image saved\n",
      "949 valid image saved\n",
      "950 valid image saved\n",
      "951 valid image saved\n",
      "Image failed. https://yandex.ru/images/search?text=%d0%ba%d0%b0%d0%bc%d1%88%d0%be%d1%82%d1%8b%20%d0%bd%d0%b0%20%d0%bf%d0%be%d0%bf%d1%83%20%d1%84%d0%be%d1%82%d0%be&stype=image&lr=213&source=wiz&pos=2&img_url=https%3a%2f%2fobmenvsemfiles.net%2fget%2f5276839%2f1601567935550_1560395756_creamy_cumshots_free_hardcore_jpg-nashobmen.org.jpg&rpt=simage\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "952 valid image saved\n",
      "953 valid image saved\n",
      "954 valid image saved\n",
      "955 valid image saved\n",
      "956 valid image saved\n",
      "957 valid image saved\n",
      "958 valid image saved\n",
      "959 valid image saved\n",
      "960 valid image saved\n",
      "Image failed. https://imgur.com/a/t4vhtx8.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/zu75ndn.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "961 valid image saved\n",
      "Image failed. https://imgur.com/a/rvfcjsp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/8afynte.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/tl48vju.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/apm1au3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "962 valid image saved\n",
      "963 valid image saved\n",
      "964 valid image saved\n",
      "965 valid image saved\n",
      "966 valid image saved\n",
      "967 valid image saved\n",
      "968 valid image saved\n",
      "969 valid image saved\n",
      "970 valid image saved\n",
      "Image failed. https://www.allaboutbirds.org/guide/assets/photo/299689191-480px.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/apm1au3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "971 valid image saved\n",
      "972 valid image saved\n",
      "973 valid image saved\n",
      "974 valid image saved\n",
      "975 valid image saved\n",
      "976 valid image saved\n",
      "977 valid image saved\n",
      "978 valid image saved\n",
      "979 valid image saved\n",
      "980 valid image saved\n",
      "981 valid image saved\n",
      "982 valid image saved\n",
      "983 valid image saved\n",
      "984 valid image saved\n",
      "985 valid image saved\n",
      "986 valid image saved\n",
      "987 valid image saved\n",
      "988 valid image saved\n",
      "989 valid image saved\n",
      "990 valid image saved\n",
      "991 valid image saved\n",
      "992 valid image saved\n",
      "993 valid image saved\n",
      "994 valid image saved\n",
      "995 valid image saved\n",
      "996 valid image saved\n",
      "997 valid image saved\n",
      "998 valid image saved\n",
      "Image failed. https://imgur.com/a/rvfcjsp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/wkfwmsz.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://img.culturacolectiva.com/content/2016/12/the-gross-middle-ages-habits.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "999 valid image saved\n",
      "1000 valid image saved\n",
      "1001 valid image saved\n",
      "1002 valid image saved\n",
      "1003 valid image saved\n",
      "Image failed. https://imgur.com/a/u5re5pv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1004 valid image saved\n",
      "Image failed. https://imgur.com/a/yhmnoik.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1005 valid image saved\n",
      "1006 valid image saved\n",
      "1007 valid image saved\n",
      "1008 valid image saved\n",
      "1009 valid image saved\n",
      "1010 valid image saved\n",
      "1011 valid image saved\n",
      "1012 valid image saved\n",
      "1013 valid image saved\n",
      "1014 valid image saved\n",
      "1015 valid image saved\n",
      "1016 valid image saved\n",
      "1017 valid image saved\n",
      "1018 valid image saved\n",
      "1019 valid image saved\n",
      "1020 valid image saved\n",
      "1021 valid image saved\n",
      "1022 valid image saved\n",
      "1023 valid image saved\n",
      "1024 valid image saved\n",
      "1025 valid image saved\n",
      "1026 valid image saved\n",
      "1027 valid image saved\n",
      "1028 valid image saved\n",
      "1029 valid image saved\n",
      "1030 valid image saved\n",
      "1031 valid image saved\n",
      "1032 valid image saved\n",
      "1033 valid image saved\n",
      "1034 valid image saved\n",
      "1035 valid image saved\n",
      "1036 valid image saved\n",
      "1037 valid image saved\n",
      "1038 valid image saved\n",
      "Image failed. https://imgur.com/a/mtx9e2w.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/s0dasea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1039 valid image saved\n",
      "Image failed. https://imgur.com/a/kscfvkl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1040 valid image saved\n",
      "1041 valid image saved\n",
      "1042 valid image saved\n",
      "1043 valid image saved\n",
      "1044 valid image saved\n",
      "1045 valid image saved\n",
      "1046 valid image saved\n",
      "1047 valid image saved\n",
      "1048 valid image saved\n",
      "1049 valid image saved\n",
      "1050 valid image saved\n",
      "1051 valid image saved\n",
      "1052 valid image saved\n",
      "1053 valid image saved\n",
      "1054 valid image saved\n",
      "1055 valid image saved\n",
      "1056 valid image saved\n",
      "1057 valid image saved\n",
      "1058 valid image saved\n",
      "1059 valid image saved\n",
      "1060 valid image saved\n",
      "1061 valid image saved\n",
      "1062 valid image saved\n",
      "1063 valid image saved\n",
      "1064 valid image saved\n",
      "1065 valid image saved\n",
      "1066 valid image saved\n",
      "1067 valid image saved\n",
      "1068 valid image saved\n",
      "1069 valid image saved\n",
      "1070 valid image saved\n",
      "1071 valid image saved\n",
      "1072 valid image saved\n",
      "1073 valid image saved\n",
      "1074 valid image saved\n",
      "1075 valid image saved\n",
      "1076 valid image saved\n",
      "1077 valid image saved\n",
      "1078 valid image saved\n",
      "1079 valid image saved\n",
      "1080 valid image saved\n",
      "1081 valid image saved\n",
      "1082 valid image saved\n",
      "1083 valid image saved\n",
      "1084 valid image saved\n",
      "1085 valid image saved\n",
      "1086 valid image saved\n",
      "1087 valid image saved\n",
      "1088 valid image saved\n",
      "Image failed. https://imgur.com/a/yj68w5u.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/336syww.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1089 valid image saved\n",
      "1090 valid image saved\n",
      "1091 valid image saved\n",
      "1092 valid image saved\n",
      "1093 valid image saved\n",
      "1094 valid image saved\n",
      "1095 valid image saved\n",
      "1096 valid image saved\n",
      "1097 valid image saved\n",
      "1098 valid image saved\n",
      "1099 valid image saved\n",
      "1100 valid image saved\n",
      "1101 valid image saved\n",
      "1102 valid image saved\n",
      "1103 valid image saved\n",
      "1104 valid image saved\n",
      "1105 valid image saved\n",
      "1106 valid image saved\n",
      "1107 valid image saved\n",
      "1108 valid image saved\n",
      "1109 valid image saved\n",
      "1110 valid image saved\n",
      "1111 valid image saved\n",
      "1112 valid image saved\n",
      "1113 valid image saved\n",
      "1114 valid image saved\n",
      "1115 valid image saved\n",
      "1116 valid image saved\n",
      "1117 valid image saved\n",
      "1118 valid image saved\n",
      "1119 valid image saved\n",
      "Image failed. https://imgur.com/a/kscfvkl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1120 valid image saved\n",
      "1121 valid image saved\n",
      "1122 valid image saved\n",
      "1123 valid image saved\n",
      "Image failed. https://imgur.com/a/nng38et.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/obxl7qw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1124 valid image saved\n",
      "1125 valid image saved\n",
      "1126 valid image saved\n",
      "1127 valid image saved\n",
      "1128 valid image saved\n",
      "1129 valid image saved\n",
      "1130 valid image saved\n",
      "1131 valid image saved\n",
      "1132 valid image saved\n",
      "1133 valid image saved\n",
      "1134 valid image saved\n",
      "1135 valid image saved\n",
      "1136 valid image saved\n",
      "1137 valid image saved\n",
      "1138 valid image saved\n",
      "1139 valid image saved\n",
      "1140 valid image saved\n",
      "1141 valid image saved\n",
      "1142 valid image saved\n",
      "1143 valid image saved\n",
      "1144 valid image saved\n",
      "1145 valid image saved\n",
      "1146 valid image saved\n",
      "1147 valid image saved\n",
      "1148 valid image saved\n",
      "1149 valid image saved\n",
      "1150 valid image saved\n",
      "1151 valid image saved\n",
      "1152 valid image saved\n",
      "1153 valid image saved\n",
      "1154 valid image saved\n",
      "1155 valid image saved\n",
      "1156 valid image saved\n",
      "1157 valid image saved\n",
      "1158 valid image saved\n",
      "1159 valid image saved\n",
      "1160 valid image saved\n",
      "1161 valid image saved\n",
      "1162 valid image saved\n",
      "1163 valid image saved\n",
      "Image failed. https://imgur.com/a/apm1au3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1164 valid image saved\n",
      "1165 valid image saved\n",
      "1166 valid image saved\n",
      "Image failed. https://imgur.com/a/c3avtke.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/klevyyd.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1167 valid image saved\n",
      "Image failed. https://imgur.com/a/m35j02h.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1168 valid image saved\n",
      "1169 valid image saved\n",
      "1170 valid image saved\n",
      "1171 valid image saved\n",
      "1172 valid image saved\n",
      "1173 valid image saved\n",
      "1174 valid image saved\n",
      "1175 valid image saved\n",
      "1176 valid image saved\n",
      "Image failed. https://imgur.com/a/m35j02h.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/hmgabdg.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1177 valid image saved\n",
      "1178 valid image saved\n",
      "1179 valid image saved\n",
      "1180 valid image saved\n",
      "1181 valid image saved\n",
      "1182 valid image saved\n",
      "1183 valid image saved\n",
      "1184 valid image saved\n",
      "1185 valid image saved\n",
      "1186 valid image saved\n",
      "1187 valid image saved\n",
      "1188 valid image saved\n",
      "1189 valid image saved\n",
      "1190 valid image saved\n",
      "1191 valid image saved\n",
      "1192 valid image saved\n",
      "1193 valid image saved\n",
      "1194 valid image saved\n",
      "1195 valid image saved\n",
      "1196 valid image saved\n",
      "1197 valid image saved\n",
      "1198 valid image saved\n",
      "1199 valid image saved\n",
      "1200 valid image saved\n",
      "1201 valid image saved\n",
      "1202 valid image saved\n",
      "1203 valid image saved\n",
      "Image failed. https://imgur.com/a/rdeuhjd.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image failed. https://imgur.com/a/wn5ivx0.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1204 valid image saved\n",
      "1205 valid image saved\n",
      "1206 valid image saved\n",
      "1207 valid image saved\n",
      "1208 valid image saved\n",
      "1209 valid image saved\n",
      "1210 valid image saved\n",
      "1211 valid image saved\n",
      "1212 valid image saved\n",
      "1213 valid image saved\n",
      "1214 valid image saved\n",
      "Image failed. https://imgur.com/a/rvfcjsp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1215 valid image saved\n",
      "1216 valid image saved\n",
      "1217 valid image saved\n",
      "1218 valid image saved\n",
      "1219 valid image saved\n",
      "1220 valid image saved\n",
      "1221 valid image saved\n",
      "Image failed. https://imgur.com/a/wrhgmno.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1222 valid image saved\n",
      "Image failed. https://imgur.com/a/6yusfa1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1223 valid image saved\n",
      "1224 valid image saved\n",
      "1225 valid image saved\n",
      "1226 valid image saved\n",
      "1227 valid image saved\n",
      "1228 valid image saved\n",
      "1229 valid image saved\n",
      "1230 valid image saved\n",
      "1231 valid image saved\n",
      "1232 valid image saved\n",
      "1233 valid image saved\n",
      "Image failed. https://www.reddit.com/gallery/opngi3\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1234 valid image saved\n",
      "1235 valid image saved\n",
      "1236 valid image saved\n",
      "1237 valid image saved\n",
      "Image failed. https://i.imgur.com/a/qflczms.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1238 valid image saved\n",
      "1239 valid image saved\n",
      "1240 valid image saved\n",
      "1241 valid image saved\n",
      "1242 valid image saved\n",
      "1243 valid image saved\n",
      "1244 valid image saved\n",
      "1245 valid image saved\n",
      "1246 valid image saved\n",
      "1247 valid image saved\n",
      "1248 valid image saved\n",
      "1249 valid image saved\n",
      "1250 valid image saved\n",
      "1251 valid image saved\n",
      "1252 valid image saved\n",
      "1253 valid image saved\n",
      "Image failed. https://imgur.com/a/fcsm4oo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/yk4bdiz.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/rvfcjsp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/wrhgmno.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/zjp5rmo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1254 valid image saved\n",
      "1255 valid image saved\n",
      "1256 valid image saved\n",
      "1257 valid image saved\n",
      "1258 valid image saved\n",
      "1259 valid image saved\n",
      "1260 valid image saved\n",
      "1261 valid image saved\n",
      "1262 valid image saved\n",
      "1263 valid image saved\n",
      "1264 valid image saved\n",
      "Image failed. https://i.imgur.com/a/xhnptt4.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1265 valid image saved\n",
      "1266 valid image saved\n",
      "1267 valid image saved\n",
      "1268 valid image saved\n",
      "1269 valid image saved\n",
      "Image failed. https://imgur.com/a/k0ibun0.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1270 valid image saved\n",
      "1271 valid image saved\n",
      "Image failed. https://imgur.com/a/qqq2d1t.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/vs6wb3m.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/8yaxfq8.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1272 valid image saved\n",
      "1273 valid image saved\n",
      "1274 valid image saved\n",
      "1275 valid image saved\n",
      "1276 valid image saved\n",
      "1277 valid image saved\n",
      "1278 valid image saved\n",
      "1279 valid image saved\n",
      "1280 valid image saved\n",
      "1281 valid image saved\n",
      "Image failed. https://imgur.com/a/qqq2d1t.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/s0dasea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1282 valid image saved\n",
      "1283 valid image saved\n",
      "1284 valid image saved\n",
      "1285 valid image saved\n",
      "1286 valid image saved\n",
      "1287 valid image saved\n",
      "1288 valid image saved\n",
      "1289 valid image saved\n",
      "1290 valid image saved\n",
      "1291 valid image saved\n",
      "1292 valid image saved\n",
      "1293 valid image saved\n",
      "1294 valid image saved\n",
      "1295 valid image saved\n",
      "1296 valid image saved\n",
      "1297 valid image saved\n",
      "1298 valid image saved\n",
      "1299 valid image saved\n",
      "1300 valid image saved\n",
      "Image failed. https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cff40e6a-cfb7-4cd8-a319-ac7cb0b7bc8c/dec6a9v-d2da5599-3f95-48a5-9291-87e86ae981ea.jpg?token=eyj0exaioijkv1qilcjhbgcioijiuzi1nij9.eyjzdwiioij1cm46yxbwojdlmgqxodg5odiynjqznznhnwywzdqxnwvhmgqynmuwiiwiaxnzijoidxjuomfwcdo3ztbkmtg4otgymjy0mzczytvmmgq0mtvlytbkmjzlmcisim9iaii6w1t7inbhdggioijcl2zcl2nmzjqwztzhlwnmyjctngnkoc1hmze5lwfjn2nimgi3ymm4y1wvzgvjnme5di1kmmrhntu5os0zzjk1ltq4ytutoti5ms04n2u4nmflotgxzweuanbnin1dxswiyxvkijpbinvybjpzzxj2awnlomzpbguuzg93bmxvywqixx0.83kkzlkk3tph0gwlx-xjkoh4vlbn16wiqod9n-fo5lc\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1301 valid image saved\n",
      "Image failed. https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cff40e6a-cfb7-4cd8-a319-ac7cb0b7bc8c/dec6a9v-d2da5599-3f95-48a5-9291-87e86ae981ea.jpg?token=eyj0exaioijkv1qilcjhbgcioijiuzi1nij9.eyjzdwiioij1cm46yxbwojdlmgqxodg5odiynjqznznhnwywzdqxnwvhmgqynmuwiiwiaxnzijoidxjuomfwcdo3ztbkmtg4otgymjy0mzczytvmmgq0mtvlytbkmjzlmcisim9iaii6w1t7inbhdggioijcl2zcl2nmzjqwztzhlwnmyjctngnkoc1hmze5lwfjn2nimgi3ymm4y1wvzgvjnme5di1kmmrhntu5os0zzjk1ltq4ytutoti5ms04n2u4nmflotgxzweuanbnin1dxswiyxvkijpbinvybjpzzxj2awnlomzpbguuzg93bmxvywqixx0.83kkzlkk3tph0gwlx-xjkoh4vlbn16wiqod9n-fo5lc\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cff40e6a-cfb7-4cd8-a319-ac7cb0b7bc8c/dec6a9v-d2da5599-3f95-48a5-9291-87e86ae981ea.jpg?token=eyj0exaioijkv1qilcjhbgcioijiuzi1nij9.eyjzdwiioij1cm46yxbwojdlmgqxodg5odiynjqznznhnwywzdqxnwvhmgqynmuwiiwiaxnzijoidxjuomfwcdo3ztbkmtg4otgymjy0mzczytvmmgq0mtvlytbkmjzlmcisim9iaii6w1t7inbhdggioijcl2zcl2nmzjqwztzhlwnmyjctngnkoc1hmze5lwfjn2nimgi3ymm4y1wvzgvjnme5di1kmmrhntu5os0zzjk1ltq4ytutoti5ms04n2u4nmflotgxzweuanbnin1dxswiyxvkijpbinvybjpzzxj2awnlomzpbguuzg93bmxvywqixx0.83kkzlkk3tph0gwlx-xjkoh4vlbn16wiqod9n-fo5lc\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1302 valid image saved\n",
      "1303 valid image saved\n",
      "1304 valid image saved\n",
      "1305 valid image saved\n",
      "1306 valid image saved\n",
      "1307 valid image saved\n",
      "1308 valid image saved\n",
      "Image failed. https://imgur.com/a/sdzousl.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1309 valid image saved\n",
      "Image failed. https://imgur.com/a/zbujtn3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/ayrumgf.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/3kvnvts.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1310 valid image saved\n",
      "1311 valid image saved\n",
      "1312 valid image saved\n",
      "1313 valid image saved\n",
      "Image failed. https://imgur.com/a/cw9ql7g.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/gezbyiw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/et0vely.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/gezbyiw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/et0vely.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/s0dasea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1314 valid image saved\n",
      "1315 valid image saved\n",
      "1316 valid image saved\n",
      "1317 valid image saved\n",
      "1318 valid image saved\n",
      "1319 valid image saved\n",
      "1320 valid image saved\n",
      "1321 valid image saved\n",
      "1322 valid image saved\n",
      "1323 valid image saved\n",
      "1324 valid image saved\n",
      "1325 valid image saved\n",
      "1326 valid image saved\n",
      "1327 valid image saved\n",
      "1328 valid image saved\n",
      "1329 valid image saved\n",
      "1330 valid image saved\n",
      "1331 valid image saved\n",
      "1332 valid image saved\n",
      "1333 valid image saved\n",
      "1334 valid image saved\n",
      "1335 valid image saved\n",
      "1336 valid image saved\n",
      "1337 valid image saved\n",
      "1338 valid image saved\n",
      "1339 valid image saved\n",
      "1340 valid image saved\n",
      "1341 valid image saved\n",
      "1342 valid image saved\n",
      "1343 valid image saved\n",
      "1344 valid image saved\n",
      "1345 valid image saved\n",
      "1346 valid image saved\n",
      "1347 valid image saved\n",
      "1348 valid image saved\n",
      "1349 valid image saved\n",
      "1350 valid image saved\n",
      "1351 valid image saved\n",
      "1352 valid image saved\n",
      "1353 valid image saved\n",
      "1354 valid image saved\n",
      "1355 valid image saved\n",
      "1356 valid image saved\n",
      "1357 valid image saved\n",
      "1358 valid image saved\n",
      "1359 valid image saved\n",
      "1360 valid image saved\n",
      "1361 valid image saved\n",
      "1362 valid image saved\n",
      "Image failed. https://external-preview.redd.it/ut-ueqomxnswaixygudjfxsyi28kaxpskq4gc1t9cns.jpg?auto=webp&s=9a2dbdbeb0c69bc5679266b33b5d9829d4415e5f\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1363 valid image saved\n",
      "1364 valid image saved\n",
      "1365 valid image saved\n",
      "1366 valid image saved\n",
      "1367 valid image saved\n",
      "1368 valid image saved\n",
      "1369 valid image saved\n",
      "1370 valid image saved\n",
      "Image failed. https://imgur.com/a/pql21uu.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1371 valid image saved\n",
      "1372 valid image saved\n",
      "1373 valid image saved\n",
      "1374 valid image saved\n",
      "1375 valid image saved\n",
      "1376 valid image saved\n",
      "1377 valid image saved\n",
      "1378 valid image saved\n",
      "1379 valid image saved\n",
      "1380 valid image saved\n",
      "1381 valid image saved\n",
      "1382 valid image saved\n",
      "1383 valid image saved\n",
      "1384 valid image saved\n",
      "1385 valid image saved\n",
      "1386 valid image saved\n",
      "1387 valid image saved\n",
      "1388 valid image saved\n",
      "1389 valid image saved\n",
      "1390 valid image saved\n",
      "1391 valid image saved\n",
      "Image failed. https://imgur.com/a/yj68w5u.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/eqtwnkp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/9wqyht5.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/z9sdom9.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/c3avtke.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/zsq2uny.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1392 valid image saved\n",
      "1393 valid image saved\n",
      "1394 valid image saved\n",
      "1395 valid image saved\n",
      "1396 valid image saved\n",
      "1397 valid image saved\n",
      "1398 valid image saved\n",
      "1399 valid image saved\n",
      "1400 valid image saved\n",
      "1401 valid image saved\n",
      "1402 valid image saved\n",
      "1403 valid image saved\n",
      "1404 valid image saved\n",
      "1405 valid image saved\n",
      "1406 valid image saved\n",
      "1407 valid image saved\n",
      "1408 valid image saved\n",
      "1409 valid image saved\n",
      "1410 valid image saved\n",
      "1411 valid image saved\n",
      "1412 valid image saved\n",
      "1413 valid image saved\n",
      "1414 valid image saved\n",
      "1415 valid image saved\n",
      "1416 valid image saved\n",
      "1417 valid image saved\n",
      "Image failed. https://imgur.com/a/t4vhtx8.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/uzjh7jg.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1418 valid image saved\n",
      "1419 valid image saved\n",
      "1420 valid image saved\n",
      "Image failed. https://imgur.com/a/s0dasea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/rdeuhjd.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/pbctnu1.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1421 valid image saved\n",
      "1422 valid image saved\n",
      "1423 valid image saved\n",
      "1424 valid image saved\n",
      "Image failed. https://imgur.com/a/ilcbl5t.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/bpjuvcv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1425 valid image saved\n",
      "1426 valid image saved\n",
      "1427 valid image saved\n",
      "1428 valid image saved\n",
      "1429 valid image saved\n",
      "1430 valid image saved\n",
      "1431 valid image saved\n",
      "1432 valid image saved\n",
      "1433 valid image saved\n",
      "1434 valid image saved\n",
      "1435 valid image saved\n",
      "1436 valid image saved\n",
      "1437 valid image saved\n",
      "1438 valid image saved\n",
      "1439 valid image saved\n",
      "1440 valid image saved\n",
      "1441 valid image saved\n",
      "1442 valid image saved\n",
      "1443 valid image saved\n",
      "1444 valid image saved\n",
      "1445 valid image saved\n",
      "1446 valid image saved\n",
      "1447 valid image saved\n",
      "1448 valid image saved\n",
      "1449 valid image saved\n",
      "1450 valid image saved\n",
      "Image failed. https://imgur.com/a/2gpnkpo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/n9luv7g.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1451 valid image saved\n",
      "1452 valid image saved\n",
      "1453 valid image saved\n",
      "1454 valid image saved\n",
      "1455 valid image saved\n",
      "1456 valid image saved\n",
      "1457 valid image saved\n",
      "1458 valid image saved\n",
      "1459 valid image saved\n",
      "1460 valid image saved\n",
      "1461 valid image saved\n",
      "1462 valid image saved\n",
      "1463 valid image saved\n",
      "1464 valid image saved\n",
      "1465 valid image saved\n",
      "1466 valid image saved\n",
      "1467 valid image saved\n",
      "1468 valid image saved\n",
      "1469 valid image saved\n",
      "1470 valid image saved\n",
      "1471 valid image saved\n",
      "1472 valid image saved\n",
      "1473 valid image saved\n",
      "1474 valid image saved\n",
      "1475 valid image saved\n",
      "1476 valid image saved\n",
      "1477 valid image saved\n",
      "1478 valid image saved\n",
      "1479 valid image saved\n",
      "1480 valid image saved\n",
      "1481 valid image saved\n",
      "1482 valid image saved\n",
      "1483 valid image saved\n",
      "1484 valid image saved\n",
      "1485 valid image saved\n",
      "1486 valid image saved\n",
      "1487 valid image saved\n",
      "1488 valid image saved\n",
      "Image failed. https://i.imgur.com/a/h861z1v.png\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1489 valid image saved\n",
      "1490 valid image saved\n",
      "1491 valid image saved\n",
      "1492 valid image saved\n",
      "Image failed. https://external-preview.redd.it/7i77mlvwi4xa3sop9fac2lmcrdn9picl5wpshmz3sby.jpg?auto=webp&s=c313b964ed947445192a914815956f41437b2798\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1493 valid image saved\n",
      "1494 valid image saved\n",
      "1495 valid image saved\n",
      "Image failed. https://imgur.com/a/s0dasea.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/obxl7qw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://cdn.imagefap.com/images/full/107/159/159657579.jpg?end=1626379053&secure=053a4571d8dec16013137\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgcodecs\\src\\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'\n",
      "\n",
      "1496 valid image saved\n",
      "1497 valid image saved\n",
      "1498 valid image saved\n",
      "1499 valid image saved\n",
      "1500 valid image saved\n",
      "1501 valid image saved\n",
      "1502 valid image saved\n",
      "1503 valid image saved\n",
      "1504 valid image saved\n",
      "1505 valid image saved\n",
      "1506 valid image saved\n",
      "1507 valid image saved\n",
      "1508 valid image saved\n",
      "1509 valid image saved\n",
      "1510 valid image saved\n",
      "1511 valid image saved\n",
      "1512 valid image saved\n",
      "1513 valid image saved\n",
      "1514 valid image saved\n",
      "1515 valid image saved\n",
      "1516 valid image saved\n",
      "1517 valid image saved\n",
      "1518 valid image saved\n",
      "1519 valid image saved\n",
      "1520 valid image saved\n",
      "1521 valid image saved\n",
      "1522 valid image saved\n",
      "1523 valid image saved\n",
      "1524 valid image saved\n",
      "1525 valid image saved\n",
      "1526 valid image saved\n",
      "1527 valid image saved\n",
      "1528 valid image saved\n",
      "1529 valid image saved\n",
      "1530 valid image saved\n",
      "1531 valid image saved\n",
      "1532 valid image saved\n",
      "1533 valid image saved\n",
      "1534 valid image saved\n",
      "1535 valid image saved\n",
      "1536 valid image saved\n",
      "1537 valid image saved\n",
      "1538 valid image saved\n",
      "1539 valid image saved\n",
      "Image failed. https://imgur.com/a/pbvfknq.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1540 valid image saved\n",
      "1541 valid image saved\n",
      "Image failed. https://imgur.com/a/kgpbp1g.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1542 valid image saved\n",
      "1543 valid image saved\n",
      "1544 valid image saved\n",
      "1545 valid image saved\n",
      "1546 valid image saved\n",
      "Image failed. https://imgur.com/a/zxrenwv.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/pxfrgbk.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/halq0m3.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/rdeuhjd.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1547 valid image saved\n",
      "1548 valid image saved\n",
      "1549 valid image saved\n",
      "1550 valid image saved\n",
      "1551 valid image saved\n",
      "1552 valid image saved\n",
      "1553 valid image saved\n",
      "1554 valid image saved\n",
      "1555 valid image saved\n",
      "1556 valid image saved\n",
      "1557 valid image saved\n",
      "1558 valid image saved\n",
      "1559 valid image saved\n",
      "1560 valid image saved\n",
      "1561 valid image saved\n",
      "1562 valid image saved\n",
      "1563 valid image saved\n",
      "1564 valid image saved\n",
      "1565 valid image saved\n",
      "1566 valid image saved\n",
      "1567 valid image saved\n",
      "1568 valid image saved\n",
      "1569 valid image saved\n",
      "1570 valid image saved\n",
      "1571 valid image saved\n",
      "1572 valid image saved\n",
      "1573 valid image saved\n",
      "1574 valid image saved\n",
      "1575 valid image saved\n",
      "1576 valid image saved\n",
      "1577 valid image saved\n",
      "1578 valid image saved\n",
      "Image failed. https://cdn.imagefap.com/images/full/107/159/159657579.jpg?end=1626213732&secure=071e2a963508dc1ed3d3f\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgcodecs\\src\\loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'\n",
      "\n",
      "1579 valid image saved\n",
      "1580 valid image saved\n",
      "1581 valid image saved\n",
      "Image failed. https://imgur.com/a/zolsmwo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/obxl7qw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1582 valid image saved\n",
      "1583 valid image saved\n",
      "Image failed. https://imgur.com/a/obxl7qw.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/tjhvgxk.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/1e1a9ki.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/eqtwnkp.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1584 valid image saved\n",
      "1585 valid image saved\n",
      "1586 valid image saved\n",
      "1587 valid image saved\n",
      "1588 valid image saved\n",
      "Image failed. https://imgur.com/a/mbbjgvh.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1589 valid image saved\n",
      "1590 valid image saved\n",
      "Image failed. https://imgur.com/a/zjp5rmo.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "Image failed. https://imgur.com/a/pjfk8ez.jpg\n",
      "OpenCV(4.4.0) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-9d_dfo3_\\opencv\\modules\\imgproc\\src\\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'\n",
      "\n",
      "1591 valid image saved\n",
      "1592 valid image saved\n",
      "1593 valid image saved\n",
      "1594 valid image saved\n",
      "1595 valid image saved\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2761, in safe_execfile\n",
      "    py3compat.execfile(\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\utils\\py3compat.py\", line 168, in execfile\n",
      "    exec(compiler(f.read(), fname, 'exec'), glob, loc)\n",
      "  File \"C:\\Users\\Jérôme\\Desktop\\GANbang\\image_scrapping\\RedditImageScraper\\SubDownload.py\", line 71, in <module>\n",
      "    resp = requests.get(submission.url.lower(), stream=True).raw\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\api.py\", line 76, in get\n",
      "    return request('get', url, params=params, **kwargs)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\api.py\", line 61, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\adapters.py\", line 439, in send\n",
      "    resp = conn.urlopen(\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\", line 670, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\", line 426, in _make_request\n",
      "    six.raise_from(e, None)\n",
      "  File \"<string>\", line 3, in raise_from\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\", line 421, in _make_request\n",
      "    httplib_response = conn.getresponse()\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\http\\client.py\", line 1348, in getresponse\n",
      "    response.begin()\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\http\\client.py\", line 316, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\http\\client.py\", line 277, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\socket.py\", line 669, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\ssl.py\", line 1241, in recv_into\n",
      "    return self.read(nbytes, buffer)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\ssl.py\", line 1099, in read\n",
      "    return self._sslobj.read(len, buffer)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2061, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\inspect.py\", line 1515, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\inspect.py\", line 1473, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\Jérôme\\.conda\\envs\\GANbang\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "object of type 'NoneType' has no len()",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36msafe_execfile\u001b[1;34m(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)\u001b[0m\n\u001b[0;32m   2760\u001b[0m                 \u001b[0mglob\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mloc\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mwhere\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;33m(\u001b[0m\u001b[1;32mNone\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;36m2\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2761\u001b[1;33m                 py3compat.execfile(\n\u001b[0m\u001b[0;32m   2762\u001b[0m                     \u001b[0mfname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mglob\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mloc\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\utils\\py3compat.py\u001b[0m in \u001b[0;36mexecfile\u001b[1;34m(fname, glob, loc, compiler)\u001b[0m\n\u001b[0;32m    167\u001b[0m         \u001b[0mcompiler\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcompiler\u001b[0m \u001b[1;32mor\u001b[0m \u001b[0mcompile\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 168\u001b[1;33m         \u001b[0mexec\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mcompiler\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'exec'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mglob\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mloc\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    169\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Desktop\\GANbang\\image_scrapping\\RedditImageScraper\\SubDownload.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     70\u001b[0m       \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 71\u001b[1;33m           \u001b[0mresp\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msubmission\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mlower\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstream\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mraw\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     72\u001b[0m           \u001b[0mimage\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0masarray\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mbytearray\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"uint8\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(url, params, **kwargs)\u001b[0m\n\u001b[0;32m     75\u001b[0m     \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'allow_redirects'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 76\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'get'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     77\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\api.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(method, url, **kwargs)\u001b[0m\n\u001b[0;32m     60\u001b[0m     \u001b[1;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 61\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0murl\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     62\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    529\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 530\u001b[1;33m         \u001b[0mresp\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    531\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\sessions.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    642\u001b[0m         \u001b[1;31m# Send the request\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 643\u001b[1;33m         \u001b[0mr\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    644\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\requests\\adapters.py\u001b[0m in \u001b[0;36msend\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    438\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mchunked\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 439\u001b[1;33m                 resp = conn.urlopen(\n\u001b[0m\u001b[0;32m    440\u001b[0m                     \u001b[0mmethod\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmethod\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[0;32m    669\u001b[0m             \u001b[1;31m# Make the request on the httplib connection object.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 670\u001b[1;33m             httplib_response = self._make_request(\n\u001b[0m\u001b[0;32m    671\u001b[0m                 \u001b[0mconn\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    425\u001b[0m                     \u001b[1;31m# Otherwise it looks like a bug in the code.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 426\u001b[1;33m                     \u001b[0msix\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mraise_from\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    427\u001b[0m         \u001b[1;32mexcept\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mSocketError\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\packages\\six.py\u001b[0m in \u001b[0;36mraise_from\u001b[1;34m(value, from_value)\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\urllib3\\connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[1;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[0;32m    420\u001b[0m                 \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 421\u001b[1;33m                     \u001b[0mhttplib_response\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgetresponse\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    422\u001b[0m                 \u001b[1;32mexcept\u001b[0m \u001b[0mBaseException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\http\\client.py\u001b[0m in \u001b[0;36mgetresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1347\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1348\u001b[1;33m                 \u001b[0mresponse\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbegin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1349\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\http\\client.py\u001b[0m in \u001b[0;36mbegin\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    315\u001b[0m         \u001b[1;32mwhile\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 316\u001b[1;33m             \u001b[0mversion\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstatus\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mreason\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_read_status\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    317\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mstatus\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[0mCONTINUE\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\http\\client.py\u001b[0m in \u001b[0;36m_read_status\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    276\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_read_status\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 277\u001b[1;33m         \u001b[0mline\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreadline\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0m_MAXLINE\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"iso-8859-1\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    278\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mline\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m>\u001b[0m \u001b[0m_MAXLINE\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\socket.py\u001b[0m in \u001b[0;36mreadinto\u001b[1;34m(self, b)\u001b[0m\n\u001b[0;32m    668\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 669\u001b[1;33m                 \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sock\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrecv_into\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    670\u001b[0m             \u001b[1;32mexcept\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\ssl.py\u001b[0m in \u001b[0;36mrecv_into\u001b[1;34m(self, buffer, nbytes, flags)\u001b[0m\n\u001b[0;32m   1240\u001b[0m                   self.__class__)\n\u001b[1;32m-> 1241\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnbytes\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbuffer\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1242\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\ssl.py\u001b[0m in \u001b[0;36mread\u001b[1;34m(self, len, buffer)\u001b[0m\n\u001b[0;32m   1098\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mbuffer\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1099\u001b[1;33m                 \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_sslobj\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbuffer\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1100\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2060\u001b[0m                         \u001b[1;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2061\u001b[1;33m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2062\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<timed eval>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mrun_line_magic\u001b[1;34m(self, magic_name, line, _stack_depth)\u001b[0m\n\u001b[0;32m   2346\u001b[0m                 \u001b[0mkwargs\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'local_ns'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_local_scope\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mstack_depth\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2347\u001b[0m             \u001b[1;32mwith\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbuiltin_trap\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2348\u001b[1;33m                 \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2349\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2350\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\decorator.py\u001b[0m in \u001b[0;36mfun\u001b[1;34m(*args, **kw)\u001b[0m\n\u001b[0;32m    230\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mkwsyntax\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    231\u001b[0m                 \u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkw\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfix\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkw\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msig\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 232\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mcaller\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfunc\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mextras\u001b[0m \u001b[1;33m+\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkw\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    233\u001b[0m     \u001b[0mfun\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    234\u001b[0m     \u001b[0mfun\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__doc__\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__doc__\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\magic.py\u001b[0m in \u001b[0;36m<lambda>\u001b[1;34m(f, *a, **k)\u001b[0m\n\u001b[0;32m    185\u001b[0m     \u001b[1;31m# but it's overkill for just that one bit of state.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    186\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mmagic_deco\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0marg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 187\u001b[1;33m         \u001b[0mcall\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mlambda\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[0ma\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0ma\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    188\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    189\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mcallable\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0marg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\magics\\execution.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, parameter_s, runner, file_finder)\u001b[0m\n\u001b[0;32m    834\u001b[0m                     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    835\u001b[0m                         \u001b[1;31m# regular execution\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 836\u001b[1;33m                         \u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    837\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    838\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[1;34m'i'\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mopts\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\magics\\execution.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m()\u001b[0m\n\u001b[0;32m    819\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    820\u001b[0m                         \u001b[1;32mdef\u001b[0m \u001b[0mrun\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 821\u001b[1;33m                             runner(filename, prog_ns, prog_ns,\n\u001b[0m\u001b[0;32m    822\u001b[0m                                     exit_ignore=exit_ignore)\n\u001b[0;32m    823\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36msafe_execfile\u001b[1;34m(self, fname, exit_ignore, raise_exceptions, shell_futures, *where)\u001b[0m\n\u001b[0;32m   2781\u001b[0m                     \u001b[1;32mraise\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2782\u001b[0m                 \u001b[1;31m# tb offset is 2 because we wrap execfile\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2783\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtb_offset\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m2\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2784\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2785\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0msafe_execfile_ipy\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mshell_futures\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mraise_exceptions\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2061\u001b[0m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2062\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2063\u001b[1;33m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0m\u001b[0;32m   2064\u001b[0m                                             value, tb, tb_offset=tb_offset)\n\u001b[0;32m   2065\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1365\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1366\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1367\u001b[1;33m         return FormattedTB.structured_traceback(\n\u001b[0m\u001b[0;32m   1368\u001b[0m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0;32m   1369\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1265\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mmode\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mverbose_modes\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1266\u001b[0m             \u001b[1;31m# Verbose modes need a full traceback\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1267\u001b[1;33m             return VerboseTB.structured_traceback(\n\u001b[0m\u001b[0;32m   1268\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1269\u001b[0m             )\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1122\u001b[0m         \u001b[1;34m\"\"\"Return a nice text document describing the traceback.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1123\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1124\u001b[1;33m         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n\u001b[0m\u001b[0;32m   1125\u001b[0m                                                                tb_offset)\n\u001b[0;32m   1126\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mformat_exception_as_a_whole\u001b[1;34m(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[0;32m   1080\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1081\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1082\u001b[1;33m         \u001b[0mlast_unique\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrecursion_repeat\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfind_recursion\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0morig_etype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrecords\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1083\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1084\u001b[0m         \u001b[0mframes\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mformat_records\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrecords\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlast_unique\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrecursion_repeat\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\GANbang\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mfind_recursion\u001b[1;34m(etype, value, records)\u001b[0m\n\u001b[0;32m    380\u001b[0m     \u001b[1;31m# first frame (from in to out) that looks different.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    381\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mis_recursion_error\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrecords\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 382\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrecords\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    383\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    384\u001b[0m     \u001b[1;31m# Select filename, lineno, func_name to track frames with\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: object of type 'NoneType' has no len()"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "%run RedditImageScraper\\SubDownload.py gonewild 2000"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e626206",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf8b097f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
